const fruits = [
  "Amla",
  "Avarekai (Field Beans )",
  "Banana Nendra",
  "Banana Rasabale",
  "Banana Yellaki",
  "Banana chandra",
  "Banana cooking R.Banana",
  "Basale Greens",
  "Beans",
  "Beans Fruit",
  "Beans cleaned",
  "Bitter Gourd",
  "Bread fruit",
  "Brinjal (W)",
  "Brinjal Bottle",
  "Byladha Hannu",
  "Cabbage Red",
  "Cabbage chaina",
  "Capsicum",
  "Carrot Delhi",
  "Carrot Nati",
  "Carrot ooty",
  "Cauliflower per Kg",
  "Chakota greens",
  "Chicco(Sapota)",
  "Chicco(Sapota) rapined",
  "Chikadi kai",
  "Chikkadikai Round",
  "Chikkadikai cleaned",
  "Chillies Bajji",
  "Chillies Cleaned",
  "Chillies Green",
  "Chillies small (C.B.P)",
  "Cluster Bean Local",
  "Corriander Leave",
  "Cowpea Long",
  "Cucumber Israle",
  "Cucumber Nati",
  "Curry leave",
  "Custerd Apple"
];

export default fruits;